MIXED_TYPE_COLUMNS: list[int] = [
    14,
    17,
    66,
    92,
    94,
    106,
    108,
    115,
    117,
    118,
    119,
    121,
    122,
    123,
    129,
    144,
    146,
    149,
    155,
    159,
    160,
    161,
    162,
    163,
    164,
    165,
    166,
    167,
    168,
    169,
    170,
    171,
    172,
    173,
    174,
    175,
    176,
    181,
    185,
    186,
    188,
    189,
]

COLUMN_TYPE_MATCHING: dict[str, str] = {
    "NU_NOTIFIC": "Int64",
    "DT_NOTIFIC": "Float64",
    "SEM_NOT": "Int64",
    "DT_SIN_PRI": "Float64",
    "SEM_PRI": "Int64",
    "SG_UF_NOT": "Categorical",
    "ID_REGIONA": "Categorical",
    "CO_REGIONA": "Float64",
    "ID_MUNICIP": "Categorical",
    "CO_MUN_NOT": "Float64",
    "CS_SEXO": "Categorical",
    "DT_NASC": "Float64",
    "NU_IDADE_N": "Int64",
    "TP_IDADE": "Int64",
    "COD_IDADE": "Int64",
    "CS_GESTANT": "Int64",
    "CS_RACA": "Float64",
    "CS_ETINIA": "Categorical",
    "CS_ESCOL_N": "Float64",
    "ID_PAIS": "Categorical",
    "CO_PAIS": "Float64",
    "SG_UF": "Categorical",
    "ID_RG_RESI": "Categorical",
    "CO_RG_RESI": "Float64",
    "ID_MN_RESI": "Categorical",
    "CO_MUN_RES": "Float64",
    "CS_ZONA": "Float64",
    "NOSOCOMIAL": "Float64",
    "AVE_SUINO": "Float64",
    "FEBRE": "Float64",
    "TOSSE": "Float64",
    "GARGANTA": "Float64",
    "DISPNEIA": "Float64",
    "DESC_RESP": "Float64",
    "SATURACAO": "Float64",
    "DIARREIA": "Float64",
    "VOMITO": "Float64",
    "OUTRO_SIN": "Float64",
    "OUTRO_DES": "Categorical",
    "FATOR_RISC": "Float64",
    "PUERPERA": "Float64",
    "CARDIOPATI": "Float64",
    "HEMATOLOGI": "Float64",
    "SIND_DOWN": "Float64",
    "HEPATICA": "Float64",
    "ASMA": "Float64",
    "DIABETES": "Float64",
    "NEUROLOGIC": "Float64",
    "PNEUMOPATI": "Float64",
    "IMUNODEPRE": "Float64",
    "RENAL": "Float64",
    "OBESIDADE": "Float64",
    "OBES_IMC": "Float64",
    "OUT_MORBI": "Float64",
    "MORB_DESC": "UTF8",
    "TABAG": "Float64",
    "VACINA": "Float64",
    "DT_UT_DOSE": "Float64",
    "MAE_VAC": "Float64",
    "DT_VAC_MAE": "Float64",
    "M_AMAMENTA": "Float64",
    "DT_DOSEUNI": "Float64",
    "DT_1_DOSE": "Float64",
    "DT_2_DOSE": "Float64",
    "ANTIVIRAL": "Float64",
    "TP_ANTIVIR": "Float64",
    "OUT_ANTIV": "Categorical",
    "DT_ANTIVIR": "Float64",
    "HOSPITAL": "Float64",
    "DT_INTERNA": "Float64",
    "SG_UF_INTE": "Categorical",
    "ID_RG_INTE": "Categorical",
    "CO_RG_INTE": "Float64",
    "ID_MN_INTE": "Categorical",
    "CO_MU_INTE": "Float64",
    "NM_UN_INTE": "Categorical",
    "UTI": "Float64",
    "DT_ENTUTI": "Float64",
    "DT_SAIDUTI": "Float64",
    "SUPORT_VEN": "Float64",
    "RAIOX_RES": "Float64",
    "RAIOX_OUT": "Categorical",
    "DT_RAIOX": "Float64",
    "AMOSTRA": "Float64",
    "DT_COLETA": "Float64",
    "TP_AMOSTRA": "Float64",
    "OUT_AMOST": "Categorical",
    "PCR_RESUL": "Float64",
    "DT_PCR": "Float64",
    "POS_PCRFLU": "Float64",
    "TP_FLU_PCR": "Float64",
    "PCR_FLUASU": "Float64",
    "FLUASU_OUT": "Categorical",
    "PCR_FLUBLI": "Float64",
    "FLUBLI_OUT": "Categorical",
    "POS_PCROUT": "Float64",
    "PCR_VSR": "Float64",
    "PCR_PARA1": "Float64",
    "PCR_PARA2": "Float64",
    "PCR_PARA3": "Float64",
    "PCR_PARA4": "Float64",
    "PCR_ADENO": "Float64",
    "PCR_METAP": "Float64",
    "PCR_BOCA": "Float64",
    "PCR_RINO": "Float64",
    "PCR_OUTRO": "Float64",
    "DS_PCR_OUT": "Categorical",
    "CLASSI_FIN": "Float64",
    "CLASSI_OUT": "Categorical",
    "CRITERIO": "Float64",
    "EVOLUCAO": "Float64",
    "DT_EVOLUCA": "Float64",
    "DT_ENCERRA": "Float64",
    "DT_DIGITA": "Float64",
    "HISTO_VGM": "Int64",
    "PAIS_VGM": "Categorical",
    "CO_PS_VGM": "Float64",
    "LO_PS_VGM": "Categorical",
    "DT_VGM": "Categorical",
    "DT_RT_VGM": "Categorical",
    "PCR_SARS2": "Float64",
    "PAC_COCBO": "Categorical",
    "PAC_DSCBO": "Categorical",
    "OUT_ANIM": "Categorical",
    "DOR_ABD": "Float64",
    "FADIGA": "Float64",
    "PERD_OLFT": "Float64",
    "PERD_PALA": "Float64",
    "TOMO_RES": "Float64",
    "TOMO_OUT": "Categorical",
    "DT_TOMO": "Float64",
    "TP_TES_AN": "Float64",
    "DT_RES_AN": "Float64",
    "RES_AN": "Float64",
    "POS_AN_FLU": "Float64",
    "TP_FLU_AN": "Float64",
    "POS_AN_OUT": "Float64",
    "AN_SARS2": "Float64",
    "AN_VSR": "Float64",
    "AN_PARA1": "Float64",
    "AN_PARA2": "Float64",
    "AN_PARA3": "Float64",
    "AN_ADENO": "Float64",
    "AN_OUTRO": "Float64",
    "DS_AN_OUT": "Categorical",
    "TP_AM_SOR": "Float64",
    "SOR_OUT": "Categorical",
    "DT_CO_SOR": "Float64",
    "TP_SOR": "Float64",
    "OUT_SOR": "Categorical",
    "DT_RES": "Float64",
    "RES_IGG": "Float64",
    "RES_IGM": "Float64",
    "RES_IGA": "Float64",
    "POV_CT": "Float64",
    "TP_POV_CT": "Categorical",
    "TEM_CPF": "Float64",
    "ESTRANG": "Float64",
    "VACINA_COV": "Float64",
    "DOSE_1_COV": "Categorical",
    "DOSE_2_COV": "Categorical",
    "DOSE_REF": "Categorical",
    "DOSE_2REF": "Categorical",
    "DOSE_ADIC": "Categorical",
    "DOS_RE_BI": "Categorical",
    "FAB_COV_1": "Categorical",
    "FAB_COV_2": "Categorical",
    "FAB_COVRF": "Categorical",
    "FAB_COVRF2": "Categorical",
    "FAB_ADIC": "Categorical",
    "FAB_RE_BI": "Categorical",
    "LOTE_1_COV": "Categorical",
    "LOTE_2_COV": "Categorical",
    "LOTE_REF": "Categorical",
    "LOTE_REF2": "Categorical",
    "LOTE_ADIC": "Categorical",
    "LOT_RE_BI": "Categorical",
    "FNT_IN_COV": "Float64",
    "TRAT_COV": "Float64",
    "TIPO_TRAT": "Float64",
    "DT_TRT_COV": "Float64",
    "OUT_TRAT": "Categorical",
    "SURTO_SG": "Float64",
    "CO_DETEC": "Float64",
    "VG_OMS": "Float64",
    "VG_OMSOUT": "Categorical",
    "VG_LIN": "Categorical",
    "VG_MET": "Float64",
    "VG_METOUT": "Float64",
    "VG_DTRES": "Categorical",
    "VG_ENC": "Float64",
    "VG_REINF": "Float64",
    "VG_CODEST": "Float64",
    "REINF": "Float64",
}
# Dicionário de tipos de dados (dtypes) para o dataset SRAG
SRAG_DTYPES = {
    # --- Dtypes para carregar de CSV ou para uso geral em Pandas ---
    "csv_pandas": {
        # Identificadores (tratar como string para evitar perda de zeros ou conversão)
        "NU_NOTIFIC": "string",
        "CO_MUN_NOT": "string",
        "CO_UNI_NOT": "string",
        "NU_CPF": "string",
        "NU_CNS": "string",
        "CO_MUN_RES": "string",
        "CO_RG_RESI": "string",
        "NM_LOGRADO": "string",
        "NU_NUMERO": "string",
        "CO_PAIS": "string",
        "CO_LAB_AN": "string",
        "REQUI_GAL": "string",
        "CO_LAB_PCR": "string",
        "VG_CODLAB": "string",
        "VG_CODDEST": "string",
        "REG_PROF": "string",
        # Datas (converter para o tipo datetime do pandas)
        "DT_NOTIFIC": "datetime64[ns]",
        "DT_SIN_PRI": "datetime64[ns]",
        "DT_NASC": "datetime64[ns]",
        "DOSE_1_COV": "datetime64[ns]",
        "DOSE_2_COV": "datetime64[ns]",
        "DOSE_REF": "datetime64[ns]",
        "DOSE_2REF": "datetime64[ns]",
        "DOSE_ADIC": "datetime64[ns]",
        "DOS_RE_BI": "datetime64[ns]",
        "DT_UT_DOSE": "datetime64[ns]",
        "DT_VAC_MAE": "datetime64[ns]",
        "DT_DOSEUNI": "datetime64[ns]",
        "DT_1_DOSE": "datetime64[ns]",
        "DT_2_DOSE": "datetime64[ns]",
        "DT_ANTIVIR": "datetime64[ns]",
        "DT_TRT_COV": "datetime64[ns]",
        "DT_INTERNA": "datetime64[ns]",
        "DT_ENTUTI": "datetime64[ns]",
        "DT_SAIDUTI": "datetime64[ns]",
        "DT_RAIOX": "datetime64[ns]",
        "DT_TOMO": "datetime64[ns]",
        "DT_COLETA": "datetime64[ns]",
        "DT_RES_AN": "datetime64[ns]",
        "DT_PCR": "datetime64[ns]",
        "DT_CO_SOR": "datetime64[ns]",
        "DT_RES": "datetime64[ns]",
        "DT_EVOLUCA": "datetime64[ns]",
        "DT_ENCERRA": "datetime64[ns]",
        "DT_DIGITA": "datetime64[ns]",
        "VG_DTRES": "datetime64[ns]",
        # Campos Categóricos (códigos numéricos ou de texto com poucas variações)
        "SEM_NOT": "string",  # Ex: 202301
        "SEM_PRI": "string",
        "SG_UF_NOT": "category",
        "CS_SEXO": "category",
        "TP_IDADE": "category",
        "CS_GESTANT": "category",
        "CS_RACA": "category",
        "CS_ETINIA": "category",
        "CS_ESCOL_N": "category",
        "SG_UF": "category",
        "CS_ZONA": "category",
        "NOSOCOMIAL": "category",
        "FEBRE": "category",
        "TOSSE": "category",
        "GARGANTA": "category",
        "DISPNEIA": "category",
        "DESC_RESP": "category",
        "SATURACAO": "category",
        "DIARREIA": "category",
        "VOMITO": "category",
        "DOR_ABD": "category",
        "FADIGA": "category",
        "PERD_OLFT": "category",
        "PERD_PALA": "category",
        "FATOR_RISC": "category",
        "PUERPERA": "category",
        "CARDIOPATI": "category",
        "HEMATOLOGI": "category",
        "SIND_DOWN": "category",
        "HEPATICA": "category",
        "ASMA": "category",
        "DIABETES": "category",
        "NEUROLOGIC": "category",
        "PNEUMOPATI": "category",
        "IMUNODEPRE": "category",
        "RENAL": "category",
        "OBESIDADE": "category",
        "TABAG": "category",
        "VACINA_COV": "category",
        "VACINA": "category",
        "ANTIVIRAL": "category",
        "TP_ANTIVIR": "category",
        "HOSPITAL": "category",
        "UTI": "category",
        "SUPORT_VEN": "category",
        "RAIOX_RES": "category",
        "TOMO_RES": "category",
        "AMOSTRA": "category",
        "TP_AMOSTRA": "category",
        "TP_TES_AN": "category",
        "RES_AN": "category",
        "PCR_RESUL": "category",
        "CLASSI_FIN": "category",
        "CRITERIO": "category",
        "EVOLUCAO": "category",
        "VG_OMS": "category",
        "VG_ENC": "category",
        "VG_REINF": "category",
        # Números Inteiros (usar tipo nullable Int64 para suportar valores ausentes)
        "NU_IDADE_N": "Int64",
        # Números de Ponto Flutuante (decimais)
        "OBES_IMC": "float64",
        # Texto livre
        "NM_PACIENT": "string",
        "NM_MAE_PAC": "string",
        "OUTRO_DES": "string",
        "MORB_DESC": "string",
        "OUT_ANIM": "string",
        "RAIOX_OUT": "string",
        "TOMO_OUT": "string",
        "OUT_AMOST": "string",
        "DS_AN_OUT": "string",
        "CLASSI_OUT": "string",
        "OBSERVA": "string",
        "NOME_PROF": "string",
        "VG_OMSOUT": "string",
        "VG_LIN": "string",
        "VG_METOUT": "string",
        "VG_LAB": "string",
        "VG_PROF": "string",
        "VG_EST": "string",
    },
    # --- Tipos para criar tabela em SQLite ---
    "sqlite": {
        # Identificadores e texto
        "NU_NOTIFIC": "TEXT",
        "NM_PACIENT": "TEXT",
        "DT_NOTIFIC": "TEXT",
        "CO_MUN_NOT": "TEXT",
        "CO_UNI_NOT": "TEXT",
        "NU_CPF": "TEXT",
        "NU_CNS": "TEXT",
        "NM_MAE_PAC": "TEXT",
        "NM_LOGRADO": "TEXT",
        "NU_NUMERO": "TEXT",
        "CO_PAIS": "TEXT",
        "OUTRO_DES": "TEXT",
        "MORB_DESC": "TEXT",
        "OUT_ANIM": "TEXT",
        "RAIOX_OUT": "TEXT",
        "TOMO_OUT": "TEXT",
        "OUT_AMOST": "TEXT",
        "DS_AN_OUT": "TEXT",
        "CLASSI_OUT": "TEXT",
        "OBSERVA": "TEXT",
        "NOME_PROF": "TEXT",
        "REG_PROF": "TEXT",
        "VG_OMSOUT": "TEXT",
        "VG_LIN": "TEXT",
        "VG_METOUT": "TEXT",
        "VG_LAB": "TEXT",
        "VG_PROF": "TEXT",
        "VG_EST": "TEXT",
        "CO_LAB_AN": "TEXT",
        "REQUI_GAL": "TEXT",
        "CO_LAB_PCR": "TEXT",
        "VG_CODLAB": "TEXT",
        "VG_CODDEST": "TEXT",
        "SEM_NOT": "TEXT",
        "SEM_PRI": "TEXT",
        # Datas (armazenar como TEXT no formato ISO 8601 'YYYY-MM-DD')
        "DT_SIN_PRI": "TEXT",
        "DT_NASC": "TEXT",
        "DOSE_1_COV": "TEXT",
        "DOSE_2_COV": "TEXT",
        "DOSE_REF": "TEXT",
        "DOSE_2REF": "TEXT",
        "DOSE_ADIC": "TEXT",
        "DOS_RE_BI": "TEXT",
        "DT_UT_DOSE": "TEXT",
        "DT_VAC_MAE": "TEXT",
        "DT_DOSEUNI": "TEXT",
        "DT_1_DOSE": "TEXT",
        "DT_2_DOSE": "TEXT",
        "DT_ANTIVIR": "TEXT",
        "DT_TRT_COV": "TEXT",
        "DT_INTERNA": "TEXT",
        "DT_ENTUTI": "TEXT",
        "DT_SAIDUTI": "TEXT",
        "DT_RAIOX": "TEXT",
        "DT_TOMO": "TEXT",
        "DT_COLETA": "TEXT",
        "DT_RES_AN": "TEXT",
        "DT_PCR": "TEXT",
        "DT_CO_SOR": "TEXT",
        "DT_RES": "TEXT",
        "DT_EVOLUCA": "TEXT",
        "DT_ENCERRA": "TEXT",
        "DT_DIGITA": "TEXT",
        "VG_DTRES": "TEXT",
        # Códigos e categorias (armazenar como INTEGER é mais eficiente)
        "SG_UF_NOT": "INTEGER",
        "CS_SEXO": "INTEGER",
        "TP_IDADE": "INTEGER",
        "CS_GESTANT": "INTEGER",
        "CS_RACA": "INTEGER",
        "CS_ETINIA": "INTEGER",
        "CS_ESCOL_N": "INTEGER",
        "SG_UF": "INTEGER",
        "CS_ZONA": "INTEGER",
        "NOSOCOMIAL": "INTEGER",
        "FEBRE": "INTEGER",
        "TOSSE": "INTEGER",
        "GARGANTA": "INTEGER",
        "DISPNEIA": "INTEGER",
        "DESC_RESP": "INTEGER",
        "SATURACAO": "INTEGER",
        "DIARREIA": "INTEGER",
        "VOMITO": "INTEGER",
        "DOR_ABD": "INTEGER",
        "FADIGA": "INTEGER",
        "PERD_OLFT": "INTEGER",
        "PERD_PALA": "INTEGER",
        "FATOR_RISC": "INTEGER",
        "PUERPERA": "INTEGER",
        "CARDIOPATI": "INTEGER",
        "HEMATOLOGI": "INTEGER",
        "SIND_DOWN": "INTEGER",
        "HEPATICA": "INTEGER",
        "ASMA": "INTEGER",
        "DIABETES": "INTEGER",
        "NEUROLOGIC": "INTEGER",
        "PNEUMOPATI": "INTEGER",
        "IMUNODEPRE": "INTEGER",
        "RENAL": "INTEGER",
        "OBESIDADE": "INTEGER",
        "TABAG": "INTEGER",
        "VACINA_COV": "INTEGER",
        "VACINA": "INTEGER",
        "ANTIVIRAL": "INTEGER",
        "TP_ANTIVIR": "INTEGER",
        "HOSPITAL": "INTEGER",
        "UTI": "INTEGER",
        "SUPORT_VEN": "INTEGER",
        "RAIOX_RES": "INTEGER",
        "TOMO_RES": "INTEGER",
        "AMOSTRA": "INTEGER",
        "TP_AMOSTRA": "INTEGER",
        "TP_TES_AN": "INTEGER",
        "RES_AN": "INTEGER",
        "PCR_RESUL": "INTEGER",
        "CLASSI_FIN": "INTEGER",
        "CRITERIO": "INTEGER",
        "EVOLUCAO": "INTEGER",
        "VG_OMS": "INTEGER",
        "VG_ENC": "INTEGER",
        "VG_REINF": "INTEGER",
        # Números
        "NU_IDADE_N": "INTEGER",
        "OBES_IMC": "REAL",
    },
    # --- Dtypes para salvar em Parquet (via Pandas) ---
    # É muito similar ao de CSV, mas reforça o uso de 'category' e 'boolean'
    # que são tipos nativos e eficientes no formato Parquet.
    "parquet_pandas": {
        # Identificadores
        "NU_NOTIFIC": "string",
        "CO_MUN_NOT": "string",
        "CO_UNI_NOT": "string",
        "NU_CPF": "string",
        "NU_CNS": "string",
        "CO_MUN_RES": "string",
        "CO_RG_RESI": "string",
        "NM_LOGRADO": "string",
        "NU_NUMERO": "string",
        "CO_PAIS": "string",
        "CO_LAB_AN": "string",
        "REQUI_GAL": "string",
        "CO_LAB_PCR": "string",
        "VG_CODLAB": "string",
        "VG_CODDEST": "string",
        "REG_PROF": "string",
        "SEM_NOT": "string",
        "SEM_PRI": "string",
        # Datas
        "DT_NOTIFIC": "datetime64[ns]",
        "DT_SIN_PRI": "datetime64[ns]",
        "DT_NASC": "datetime64[ns]",
        "DOSE_1_COV": "datetime64[ns]",
        "DOSE_2_COV": "datetime64[ns]",
        "DOSE_REF": "datetime64[ns]",
        "DOSE_2REF": "datetime64[ns]",
        "DOSE_ADIC": "datetime64[ns]",
        "DOS_RE_BI": "datetime64[ns]",
        "DT_UT_DOSE": "datetime64[ns]",
        "DT_VAC_MAE": "datetime64[ns]",
        "DT_DOSEUNI": "datetime64[ns]",
        "DT_1_DOSE": "datetime64[ns]",
        "DT_2_DOSE": "datetime64[ns]",
        "DT_ANTIVIR": "datetime64[ns]",
        "DT_TRT_COV": "datetime64[ns]",
        "DT_INTERNA": "datetime64[ns]",
        "DT_ENTUTI": "datetime64[ns]",
        "DT_SAIDUTI": "datetime64[ns]",
        "DT_RAIOX": "datetime64[ns]",
        "DT_TOMO": "datetime64[ns]",
        "DT_COLETA": "datetime64[ns]",
        "DT_RES_AN": "datetime64[ns]",
        "DT_PCR": "datetime64[ns]",
        "DT_CO_SOR": "datetime64[ns]",
        "DT_RES": "datetime64[ns]",
        "DT_EVOLUCA": "datetime64[ns]",
        "DT_ENCERRA": "datetime64[ns]",
        "DT_DIGITA": "datetime64[ns]",
        "VG_DTRES": "datetime64[ns]",
        # Campos Categóricos (muito eficiente em Parquet)
        "SG_UF_NOT": "category",
        "CS_SEXO": "category",
        "TP_IDADE": "category",
        "CS_GESTANT": "category",
        "CS_RACA": "category",
        "CS_ETINIA": "category",
        "CS_ESCOL_N": "category",
        "SG_UF": "category",
        "CS_ZONA": "category",
        "NOSOCOMIAL": "category",
        "FATOR_RISC": "category",
        "PUERPERA": "category",
        "CARDIOPATI": "category",
        "HEMATOLOGI": "category",
        "SIND_DOWN": "category",
        "HEPATICA": "category",
        "ASMA": "category",
        "DIABETES": "category",
        "NEUROLOGIC": "category",
        "PNEUMOPATI": "category",
        "IMUNODEPRE": "category",
        "RENAL": "category",
        "OBESIDADE": "category",
        "TABAG": "category",
        "VACINA_COV": "category",
        "VACINA": "category",
        "ANTIVIRAL": "category",
        "TP_ANTIVIR": "category",
        "HOSPITAL": "category",
        "UTI": "category",
        "SUPORT_VEN": "category",
        "RAIOX_RES": "category",
        "TOMO_RES": "category",
        "AMOSTRA": "category",
        "TP_AMOSTRA": "category",
        "TP_TES_AN": "category",
        "RES_AN": "category",
        "PCR_RESUL": "category",
        "CLASSI_FIN": "category",
        "CRITERIO": "category",
        "EVOLUCAO": "category",
        "VG_OMS": "category",
        "VG_ENC": "category",
        "VG_REINF": "category",
        # Booleanos (Sim/Não pode ser convertido para booleano)
        "FEBRE": "boolean",
        "TOSSE": "boolean",
        "GARGANTA": "boolean",
        "DISPNEIA": "boolean",
        "DESC_RESP": "boolean",
        "SATURACAO": "boolean",
        "DIARREIA": "boolean",
        "VOMITO": "boolean",
        "DOR_ABD": "boolean",
        "FADIGA": "boolean",
        "PERD_OLFT": "boolean",
        "PERD_PALA": "boolean",
        # Números Inteiros (nullable)
        "NU_IDADE_N": "Int64",
        # Números de Ponto Flutuante
        "OBES_IMC": "float64",
        # Texto
        "NM_PACIENT": "string",
        "NM_MAE_PAC": "string",
        "OUTRO_DES": "string",
        "MORB_DESC": "string",
        "OUT_ANIM": "string",
        "RAIOX_OUT": "string",
        "TOMO_OUT": "string",
        "OUT_AMOST": "string",
        "DS_AN_OUT": "string",
        "CLASSI_OUT": "string",
        "OBSERVA": "string",
        "NOME_PROF": "string",
        "VG_OMSOUT": "string",
        "VG_LIN": "string",
        "VG_METOUT": "string",
        "VG_LAB": "string",
        "VG_PROF": "string",
        "VG_EST": "string",
    },
}

LLM_READY_SCHEMA = """
* Patient/Notification: `NU_NOTIFIC`(ID), `NM_PACIENT`(Txt), `NM_MAE_PAC`(Txt), `NU_CPF`/`NU_CNS`(ID), `DT_NASC`(Dt), `NU_IDADE_N`(Num), `TP_IDADE`(Cat), `CS_SEXO`(Cat), `CS_RACA`(Cat), `CS_ETINIA`(ID), `CS_ESCOL_N`(Cat).
* Location: `SG_UF`/`SG_UF_NOT`(ID: State), `CO_MUN_NOT`(ID: Municipality), `CO_UNI_NOT`(ID: Health Unit), `NM_LOGRADO`(Txt: Street), `NU_NUMERO`(Txt), `CS_ZONA`(Cat), `CO_PAIS`(ID).
* Key Dates: `DT_NOTIFIC`, `DT_SIN_PRI`, `DT_INTERNA`, `DT_ENTUTI`, `DT_SAIDUTI`, `DT_RAIOX`, `DT_TOMO`, `DT_COLETA`, `DT_RES_AN`, `DT_PCR`, `DT_CO_SOR`, `DT_RES`, `DT_EVOLUCA`, `DT_ENCERRA`, `DT_DIGITA`, `DT_ANTIVIR`, `DT_TRT_COV`.
* Vaccine Dates: `DOSE_1_COV`, `DOSE_2_COV`, `DOSE_REF`, `DOSE_2REF`, `DOSE_ADIC`, `DOS_RE_BI`, `DT_UT_DOSE`, `DT_VAC_MAE`, `DT_DOSEUNI`, `DT_1_DOSE`, `DT_2_DOSE`.
* Symptoms (Y/N Flags): `FEBRE`, `TOSSE`, `GARGANTA`, `DISPNEIA`, `DESC_RESP`, `SATURACAO`, `DIARREIA`, `VOMITO`, `DOR_ABD`, `FADIGA`, `PERD_OLFT`(smell), `PERD_PALA`(taste). `OUTRO_DES`(Txt: other).
* Comorbidities (Y/N Flags): `FATOR_RISC`, `PUERPERA`, `CARDIOPATI`, `HEMATOLOGI`, `SIND_DOWN`, `HEPATICA`, `ASMA`, `DIABETES`, `NEUROLOGIC`, `PNEUMOPATI`, `IMUNODEPRE`, `RENAL`, `OBESIDADE`, `TABAG`. `MORB_DESC`(Txt), `OBES_IMC`(Txt).
* Hospitalization/Treatment: `HOSPITAL`(Y/N), `UTI`(Y/N), `NOSOCOMIAL`(Y/N), `SUPORT_VEN`(Cat), `ANTIVIRAL`(Y/N), `TP_ANTIVIR`(Cat).
* Lab & Tests:
  * Status (Y/N or Cat): `AMOSTRA`, `TP_AMOSTRA`, `TP_TES_AN`, `RES_AN`, `PCR_RESUL`, `RAIOX_RES`, `TOMO_RES`.
  * "Other" Descriptions (Txt): `OUT_AMOST`, `RAIOX_OUT`, `TOMO_OUT`, `DS_AN_OUT`.
  * Lab IDs: `CO_LAB_AN`, `CO_LAB_PCR`, `REQUI_GAL`.
* Classification & Outcome: `CLASSI_FIN`(Cat), `CLASSI_OUT`(Txt), `CRITERIO`(Cat), `EVOLUCAO`(Cat: cure/death), `VG_REINF`(reinfection Y/N).
* Genomic Surveillance: `VG_OMS`(WHO variant), `VG_LIN`(lineage), `VG_LAB`(Txt), `VG_CODLAB`(ID), `VG_PROF`(Txt), `VG_EST`(Txt), `VG_OMSOUT`(Txt), `VG_METOUT`(Txt).
* Misc: `SEM_NOT`/`SEM_PRI`(epi. week), `OUT_ANIM`(Txt), `OBSERVA`(Txt), `NOME_PROF`(Txt), `REG_PROF`(ID).

IMPORTANT QUERY GUIDELINES:
- For Y/N fields: 1=Yes, 2=No, 9=Unknown/Not filled
- Date fields may contain NULL values
- Use epidemiological weeks (SEM_NOT, SEM_PRI) for temporal aggregations
- Filter by state (SG_UF_NOT) for geographic analysis
- Common aggregations: COUNT by week, state, age group, outcome
- For mortality analysis: EVOLUCAO = 2
- For COVID-19 specific: check vaccination dates and variants
"""
