MIXED_TYPE_COLUMNS: list[int] = [
    14,
    17,
    66,
    92,
    94,
    106,
    108,
    115,
    117,
    118,
    119,
    121,
    122,
    123,
    129,
    144,
    146,
    149,
    155,
    159,
    160,
    161,
    162,
    163,
    164,
    165,
    166,
    167,
    168,
    169,
    170,
    171,
    172,
    173,
    174,
    175,
    176,
    181,
    185,
    186,
    188,
    189,
]

COLUMN_TYPE_MATCHING: dict[str, str] = {
    "NU_NOTIFIC": "Int64",
    "DT_NOTIFIC": "Float64",
    "SEM_NOT": "Int64",
    "DT_SIN_PRI": "Float64",
    "SEM_PRI": "Int64",
    "SG_UF_NOT": "Categorical",
    "ID_REGIONA": "Categorical",
    "CO_REGIONA": "Float64",
    "ID_MUNICIP": "Categorical",
    "CO_MUN_NOT": "Float64",
    "CS_SEXO": "Categorical",
    "DT_NASC": "Float64",
    "NU_IDADE_N": "Int64",
    "TP_IDADE": "Int64",
    "COD_IDADE": "Int64",
    "CS_GESTANT": "Int64",
    "CS_RACA": "Float64",
    "CS_ETINIA": "Categorical",
    "CS_ESCOL_N": "Float64",
    "ID_PAIS": "Categorical",
    "CO_PAIS": "Float64",
    "SG_UF": "Categorical",
    "ID_RG_RESI": "Categorical",
    "CO_RG_RESI": "Float64",
    "ID_MN_RESI": "Categorical",
    "CO_MUN_RES": "Float64",
    "CS_ZONA": "Float64",
    "NOSOCOMIAL": "Float64",
    "AVE_SUINO": "Float64",
    "FEBRE": "Float64",
    "TOSSE": "Float64",
    "GARGANTA": "Float64",
    "DISPNEIA": "Float64",
    "DESC_RESP": "Float64",
    "SATURACAO": "Float64",
    "DIARREIA": "Float64",
    "VOMITO": "Float64",
    "OUTRO_SIN": "Float64",
    "OUTRO_DES": "Categorical",
    "FATOR_RISC": "Float64",
    "PUERPERA": "Float64",
    "CARDIOPATI": "Float64",
    "HEMATOLOGI": "Float64",
    "SIND_DOWN": "Float64",
    "HEPATICA": "Float64",
    "ASMA": "Float64",
    "DIABETES": "Float64",
    "NEUROLOGIC": "Float64",
    "PNEUMOPATI": "Float64",
    "IMUNODEPRE": "Float64",
    "RENAL": "Float64",
    "OBESIDADE": "Float64",
    "OBES_IMC": "Float64",
    "OUT_MORBI": "Float64",
    "MORB_DESC": "Categorical",
    "TABAG": "Float64",
    "VACINA": "Float64",
    "DT_UT_DOSE": "Float64",
    "MAE_VAC": "Float64",
    "DT_VAC_MAE": "Float64",
    "M_AMAMENTA": "Float64",
    "DT_DOSEUNI": "Float64",
    "DT_1_DOSE": "Float64",
    "DT_2_DOSE": "Float64",
    "ANTIVIRAL": "Float64",
    "TP_ANTIVIR": "Float64",
    "OUT_ANTIV": "Categorical",
    "DT_ANTIVIR": "Float64",
    "HOSPITAL": "Float64",
    "DT_INTERNA": "Float64",
    "SG_UF_INTE": "Categorical",
    "ID_RG_INTE": "Categorical",
    "CO_RG_INTE": "Float64",
    "ID_MN_INTE": "Categorical",
    "CO_MU_INTE": "Float64",
    "NM_UN_INTE": "Categorical",
    "UTI": "Float64",
    "DT_ENTUTI": "Float64",
    "DT_SAIDUTI": "Float64",
    "SUPORT_VEN": "Float64",
    "RAIOX_RES": "Float64",
    "RAIOX_OUT": "Categorical",
    "DT_RAIOX": "Float64",
    "AMOSTRA": "Float64",
    "DT_COLETA": "Float64",
    "TP_AMOSTRA": "Float64",
    "OUT_AMOST": "Categorical",
    "PCR_RESUL": "Float64",
    "DT_PCR": "Float64",
    "POS_PCRFLU": "Float64",
    "TP_FLU_PCR": "Float64",
    "PCR_FLUASU": "Float64",
    "FLUASU_OUT": "Categorical",
    "PCR_FLUBLI": "Float64",
    "FLUBLI_OUT": "Categorical",
    "POS_PCROUT": "Float64",
    "PCR_VSR": "Float64",
    "PCR_PARA1": "Float64",
    "PCR_PARA2": "Float64",
    "PCR_PARA3": "Float64",
    "PCR_PARA4": "Float64",
    "PCR_ADENO": "Float64",
    "PCR_METAP": "Float64",
    "PCR_BOCA": "Float64",
    "PCR_RINO": "Float64",
    "PCR_OUTRO": "Float64",
    "DS_PCR_OUT": "Categorical",
    "CLASSI_FIN": "Float64",
    "CLASSI_OUT": "Categorical",
    "CRITERIO": "Float64",
    "EVOLUCAO": "Float64",
    "DT_EVOLUCA": "Float64",
    "DT_ENCERRA": "Float64",
    "DT_DIGITA": "Float64",
    "HISTO_VGM": "Int64",
    "PAIS_VGM": "Categorical",
    "CO_PS_VGM": "Float64",
    "LO_PS_VGM": "Categorical",
    "DT_VGM": "Categorical",
    "DT_RT_VGM": "Categorical",
    "PCR_SARS2": "Float64",
    "PAC_COCBO": "Categorical",
    "PAC_DSCBO": "Categorical",
    "OUT_ANIM": "Categorical",
    "DOR_ABD": "Float64",
    "FADIGA": "Float64",
    "PERD_OLFT": "Float64",
    "PERD_PALA": "Float64",
    "TOMO_RES": "Float64",
    "TOMO_OUT": "Categorical",
    "DT_TOMO": "Float64",
    "TP_TES_AN": "Float64",
    "DT_RES_AN": "Float64",
    "RES_AN": "Float64",
    "POS_AN_FLU": "Float64",
    "TP_FLU_AN": "Float64",
    "POS_AN_OUT": "Float64",
    "AN_SARS2": "Float64",
    "AN_VSR": "Float64",
    "AN_PARA1": "Float64",
    "AN_PARA2": "Float64",
    "AN_PARA3": "Float64",
    "AN_ADENO": "Float64",
    "AN_OUTRO": "Float64",
    "DS_AN_OUT": "Categorical",
    "TP_AM_SOR": "Float64",
    "SOR_OUT": "Categorical",
    "DT_CO_SOR": "Float64",
    "TP_SOR": "Float64",
    "OUT_SOR": "Categorical",
    "DT_RES": "Float64",
    "RES_IGG": "Float64",
    "RES_IGM": "Float64",
    "RES_IGA": "Float64",
    "POV_CT": "Float64",
    "TP_POV_CT": "Categorical",
    "TEM_CPF": "Float64",
    "ESTRANG": "Float64",
    "VACINA_COV": "Float64",
    "DOSE_1_COV": "Categorical",
    "DOSE_2_COV": "Categorical",
    "DOSE_REF": "Categorical",
    "DOSE_2REF": "Categorical",
    "DOSE_ADIC": "Categorical",
    "DOS_RE_BI": "Categorical",
    "FAB_COV_1": "Categorical",
    "FAB_COV_2": "Categorical",
    "FAB_COVRF": "Categorical",
    "FAB_COVRF2": "Categorical",
    "FAB_ADIC": "Categorical",
    "FAB_RE_BI": "Categorical",
    "LOTE_1_COV": "Categorical",
    "LOTE_2_COV": "Categorical",
    "LOTE_REF": "Categorical",
    "LOTE_REF2": "Categorical",
    "LOTE_ADIC": "Categorical",
    "LOT_RE_BI": "Categorical",
    "FNT_IN_COV": "Float64",
    "TRAT_COV": "Float64",
    "TIPO_TRAT": "Float64",
    "DT_TRT_COV": "Float64",
    "OUT_TRAT": "Categorical",
    "SURTO_SG": "Float64",
    "CO_DETEC": "Float64",
    "VG_OMS": "Float64",
    "VG_OMSOUT": "Categorical",
    "VG_LIN": "Categorical",
    "VG_MET": "Float64",
    "VG_METOUT": "Float64",
    "VG_DTRES": "Categorical",
    "VG_ENC": "Float64",
    "VG_REINF": "Float64",
    "VG_CODEST": "Float64",
    "REINF": "Float64",
}
